name: javaCI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('ProjectWithDb/pom.xml') }}
    - name: checkout code
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: compile
      run: |
        javac ProjectWithDb/src/main/java/org/example/Main.java
        java Main
    - name: run tests
      run: |
        javac ProjectWithDb/src/test/java/dbTests.java
        java dbTests.java
